### PR TITLE
Allow server-side verification of transactions.

### PR DESCRIPTION
**Pull request by mrucci**
Hi!  Thanks a lot for this handy library.

I modified the source so that the raw `signedData` and `signature` strings are stored in the BillingDB.  This way I can recover the transactions in my `onPurchaseStateChanged` callback through `BillingController.getTransactions(this)` and send to my server all the information needed to process the transaction **and perform its verification**.

It's a small modification, but I think most user will look after this feature.

### CODE REVIEW

**Comment by japostoles** [comment]
Agreed!  Thanks for this!

**Comment by guetux** [comment]
Why, hello there! Also a lot of kudos from my side for this great library, it really saved my day.

I actually had the exact same requirement as you mrucci and implemented it much the same way: http://bit.ly/MOK6Cr

The main difference is that i used the `onUpgrade` facility to support schema migration for apps that already use the library. However, i did not change the Transaction Model to require signedData and signature, i made them optional (android.test.purchased doesnt always give you a signed response for example).

I didn't test restoring purchases though. Maybe we could merge our solutions together, what do  you think?

**Comment by guetux** [comment]
Actually, i think it's important to mention here that you could also implement a custom `ISignatureValidator` and change the validator with `BillingController.setSignatureValidator()`. In our architecture however, the server doesn't save any purchases, so i want to have the receipts available in the app

**Comment by mrucci** [comment]
Yes, I agree on merging our patches.  The schema migration in particular sounds very helpful.

If I am not mistaken,  all the functionality in my patch are also in your patch, so maybe you can create a new pull request and I will close this one.

**Comment by hpique** [comment]
@mrucci Thanks for sending this. As @guetux mentioned, we need `onUpdgrade` to make sure we don't break apps that already use the library.

@guetux Can you send a pull request with https://github.com/guetux/AndroidBillingLibrary/commit/c6d8c1a981e41328c1eccb01a4a7b0b1e7903145 ?

**Comment by PabloEskimo** [comment]
What's the status of this? I also need to do server-side verification of purchase signatures.
Is this going to be merged in?

**Comment by IntegersOfK** [comment]
It would seem that @hpique want to keep this library ["as simple as possible"](https://github.com/robotmedia/AndroidBillingLibrary/pull/55#issuecomment-7364917) and may not be open to such changes. I'm new to GitHub shared projects, but perhaps @guetux or @mrucci could consider 'forking' the project to implement these other great suggestions that people have been coding? Additionally, there hasn't been a commit in 2 months, so maybe it's time to advance the project without him/her. I'm not sure about the etiquette of this proposition, obviously I mean no disrespect to @hpique.

**Comment by hpique** [comment]
@PabloEskimo Most likely in the next big update. This commit in my fork might also be of interest: https://github.com/hpique/AndroidBillingLibrary/commit/e23bc72c6178b8f03f75f3211b14deadb050c198

@IntegersOfK No offense taken. This is not related to the "as simple as possible" motto. I only update the library when I'm 99% sure I'm not breaking something, and that takes time and testing. This pull request in particular breaks stuff (see @guetux's comment).

**Comment by IntegersOfK** [comment]
@hpique Oh that's great! No worries, I'm just trying to wrap my head around this whole thing. In that case I foresee having questions about updating/upgrading after implementation, but I'll stop hijacking this thread and let the smart people do their work.

**Comment by mikefrederick** [comment]
Very very very much looking forward to seeing this implemented. Server-side verification is crucial in many situations.

**Comment by guetux** [comment]
Wow, already 4 months passed. Sorry, i forgot about this one and have been of Android development for the past 4 months as well. I rebased my fork with your current master branch and sent you a pull request.

However, it think it's important to mention again that i never tested restoring transaction in the wild yet. Can someone take care of this?

**Comment by mrucci** [comment]
Ok, closing this pull request in favor of https://github.com/robotmedia/AndroidBillingLibrary/issues/90.

**Pull request closed without merging**
