### PR TITLE
Save signedData and signature to allow server side validation

### PR DESCRIPTION
**Pull request by guetux**
This is a follow up to #58. Upgrade compatibility is guaranteed by the `onUpgrade` facility. 

Important: Before merging this pull request, someone with good knowledge of this library should test if restoring transactions work

### CODE REVIEW

**Comment by hpique** [comment]
Thanks @guetux & @mrucci! I merged this pull request in my fork, added a few unit tests and will test it a bit more before pushing it to the main fork.

https://github.com/hpique/AndroidBillingLibrary

**Comment by hpique** [comment]
@guetux, @mrucci, would you care to explain in detail why this is necessary again?

After testing it quite a bit there's 2 things I don't like about this pull request:
- Transactions are not stored in the database until they are successfully validated. What's the point of storing the signedData and signature in the database AFTER they have already been used? Unless there's a use case I'm not seeing, server-side validation should be performed BEFORE the transaction is added to the database (by providing your own ISignatureValidator).
- signedData might contain more than one transaction (unlikely, but we managed to reproduce it). When this happens, it doesn't feel right to store the whole signedData in each of the transactions.

**Comment by guetux** [comment]
Hi @hpique, they main idea of storing this data is to use is it as a receipt later. Consider a scenario where you sell digital goods downloadable from you app server. Before sending out your files you ask the app to send you the signedData and the signature of the purchase to validate that the sku is paid for. You only need to have the public key on the server to do this. It's the responsability of you app how this is implemented, but AndroidBillingLibrary should offer  at least the data to do this. That's why it's acually not a big problem if multiple transaction are made, you only need to validate that the correspondig sku was pruchased

**Comment by hpique** [comment]
@guetux My point is that the library already offers this data. That's what [ISignatureValidator](https://github.com/robotmedia/AndroidBillingLibrary/blob/master/AndroidBillingLibrary/src/net/robotmedia/billing/security/ISignatureValidator.java) is for, and we use it ourselves for server-side validation.

By implementing your own ISignatureValidator you can have remote validation, and you don't need to put your public key in the app.

The only limitation in the main fork (fixed in https://github.com/hpique/AndroidBillingLibrary/commit/e23bc72c6178b8f03f75f3211b14deadb050c198, which I will merge shortly) is that the validation was synchronous.

With that into account, do you still think storing the signedData is necessary?

The only use case I can think of of storing this information is to do an additional validation every time you redownload content but for that I would argue that it's best to use your own mechanism (such as user accounts).

**Comment by guetux** [comment]
Yes, i saw the option of using `ISignatureValidator` and mentioned it in #58 as well ;-). I agree that this would be an alternative way. However, in my case, it was a question of control flow: I would have to submit signedData and signature in ISignatureValidator to the server and start the download later (cause there's additional data I have to submit to the server). So I rather wanted to have access to this in my `BillingObserver`.

Another option would be that I'll create my own little purchase database and save the data in `ISignatureValidator` there. Then I saw that other people are looking for this feature too and thought i could send a pull request ;-). I think it's ok to drop this one if you want to keep the database slim. In this case though, I would suggest to give a short hint about `ISignatureValidator` in the README

**Comment by hpique** [comment]
@guetux Yes, I will drop this in the spirit of keeping the DB slim and improve the documentation about `ISignatureValidator`. Thanks for the discussion and the code!

**Comment by mrucci** [comment]
Yes @hpique.  `ISignatureValidator` would have been sufficient for my needs... but I missed it.  Definitely worth mentioning in the docs.

**Pull request closed without merging**
