### PR TITLE
onError-method for transaction restore failed / retry in case of remote exception

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Hi there,

I added another method to be called in case the restoring of the transactions fails. It makes sense to know if it failed to display a message on an activity or a toast to let the user know that it failed (or handle it otherwise).

Best regards
Andy

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@serso done, but I had to add a MAX_RETRIES constant

**Comment by AndyScherzinger** [comment]
@hpique You actually did not add it... You would have needed to merge ALL the changes of this pull request wouldn't you? Else would have merged the tests, the interface changes and so on.

**Comment by hpique** [comment]
@AndyScherzinger I was talking about only one of the commits.

https://github.com/AndyScherzinger/AndroidBillingLibrary/commit/e6804a8528d1cf54f5d939905b23a5b24e9e9c2c

GitHub shows commit-specific comments in the discussion of the corresponding pull request. Which is sometimes confusing.

**Comment by AndyScherzinger** [comment]
Gotcha! Thanks for that hint :)

Any reason for not merging the other changes? The retries seem to be quite useful and also the error-Method in case the transaction can't be restored which IMHO is quite an important information for the developer wouldn't you agree?

**Comment by hpique** [comment]
@AndyScherzinger I just wanted to think a little bit more about them before adding them to the library. 

In particular, I was thinking of a more generic solution to error notifications.

**Comment by AndyScherzinger** [comment]
sure thing.
You might also be interested in the changes @serso made on his fork like oberservers :)

**Comment by hpique** [comment]
I've been watching that, yes. :)

**Pull request closed without merging**
