### PR TITLE
Handling Transaction Restore Failed error

### PR DESCRIPTION
**Pull request by nqbao**
Hi all,

I just added some code to allow handling error when RESULT_SERVICE_UNAVAILABLE is returned from request. You can try this by do a fresh install of the app (uninstall and reinstall again) then turn off all connections and launch the app.

Thanks,

### CODE REVIEW

**Comment by wlowe** [comment]
At first glance, this seems like a reasonable approach.  Is it going to be merged?

**Comment by hpique** [comment]
@nopayne I'd like to keep IBillingObserver as simple as possible. Have to think about it more.

@nqbao Thanks for this and awesome avatar!

**Comment by klemensz** [comment]
From time to time I get: 
W/BillingService(13628): Remote billing service crashed
and it looks like there is currently no way to handle it or notify the user?

**Comment by hpique** [comment]
A fix for https://github.com/nqbao/AndroidBillingLibrary/commit/6882f114f7c57a6e0f8cefee6806d892fef62ba8 will be added in my next pull request. The solution is slightly different, as I'm not convinced that `onServiceError` should be part of `IBillingObserver`.

**Pull request closed without merging**
